#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (c) 2015 龔士捷 <ksc91u@gmail.com>
# Copyright (c) 2007 洪任諭 (PCMan) <pcman.tw@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os, os.path
import re
IS_PYTHON_2=False
try:
    import urllib.request as urllib2
#    import HTMLParser
    IS_PYTHON_2=True
except ImportError:
    IS_PYTHON_2=False
    import urllib2
#    import html

dir_path = os.path.expanduser('~/.config/hinedo/' )

def download( url ):
    req = urllib2.Request(url, None, {'User-agent' : 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.1.5) Gecko/20091102 Firefox/3.5.5', 'Referer' : 'http://hichannel.hinet.net/radio/index.do'})
    f = urllib2.urlopen(req)
    if f:
        content = f.read()
        f.close()
        return content
    return ''

try:
    f = open( dir_path + 'menu', 'wb' )
except:
    exit(1)

#http://hichannel.hinet.net/radio/channelList.do?
menu = download('http://hichannel.hinet.net/radio/index.do');
menu = menu.decode('UTF-8')
menu = menu.replace("\r","").replace("\n","")

reg = re.compile( '<li rel="(\d+)">.+?<div class="info">.+?<p>(.+?)</p>.+?<p class="company">(.*?)</p>.+?</div>.+?</li>', re.I|re.M |re.MULTILINE)
match = reg.findall( menu )
for m in match:
	line=m[0]+"\t"+m[1]+"\n"
	f.write(line.encode('UTF-8','UTF-8'))
f.close()
